name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'bun'
        
    - name: Install dependencies
      run: bun ci
      
    - name: Run linting
      run: bun run lint
      
    - name: Run type checking
      run: bun run typecheck
      
    - name: Build
      run: bun run build